sudo: required
services:
  - docker

before_install:
  - docker build -t rodrigodoe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rodrigodoe/docker-react npm run test
language: generic

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react-sample"
  env: "DockerReactSample-env"
  bucket_name: "elasticbeanstalk-us-east-2-043554528356"
  bucket_path: "docker-react-sample"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
