sudo: required
services:
  - docker

before_install:
  - docker build -t rodrigodoe/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true rodrigodoe/docker-react npm run test
language: generic

deploy:
  provider: elasticbeanstalk
  region: ""
  app:
  env: ""
  bucket_name: ""
  bucket_path: ""
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
